config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  root 'administration/items#index'

  get '/home', to: 'home#landing_page'

  namespace 'administration' do
    get '/', to: 'items#index'

    resources :items
    resources :profiles do
      member do
        get '/send_email', to: "profiles#send_email", as: :send_email
      end
    end
  end
end

app/models/item.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: items
#
#  id                  :bigint(8)        not null, primary key
#  original_price      :float            not null
#  has_discount        :boolean          default(FALSE)
#  discount_percentage :integer          default(0)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Item < ApplicationRecord
  def price
    80.00
  end
end

app/controllers/administration/items_controller.rb
# frozen_string_literal: true

module Administration
  class ItemsController < AdministrationController
    def index
      @emails = User.emails_of_all_users
      @items = Item.all
    end

    def update
      redirect_to administration_items_path
    end
  end
end

app/controllers/administration/profiles_controller.rb
# frozen_string_literal: true

module Administration
  class ProfilesController < ApplicationController
    before_action :set_profile

    def show; end

    def send_email
      @profile.send_email
      redirect_back fallback_location: root_path
    end

    private

    def set_profile
      @profile = Profile.find(params[:id])
    end
  end
end

app/controllers/administration_controller.rb
# frozen_string_literal: true

class AdministrationController < ApplicationController
  layout "administration"
end

app/views/administration/items/_table_row.html.erb
<%= form_for item, url: administration_item_url(item.id), html: {class: ""} do |f| %>
	<tr>
		<td> <%= item.original_price %></td>
		<td> 
	  	<%= f.text_field :discount_percentage, value: item.discount_percentage, class: "form-control" %>
				</div>
			</div>
		</td>
		<td> <%= item.price %></td>
		<td>
			<%= f.submit "Modifier", class: "btn btn-secondary"  %>
		</td>
	</tr>
<% end %>

app/views/administration/items/index.html.erb
<main class="content">
	<div class="container-fluid p-0">

		<h1 class="h3 mb-3">Items</h1>

		<h3>Emails</h3>
		<% @emails.each do |email| %>
			<p><%= email %></p>
		<% end %>

		<div class="row">
			<div class="col-12">

				<div class="card">
					<div class="table-responsive">
						<table class="table table-striped table-hover">
							<thead>
								<tr>
									<th>Prix de départ</th>
									<th>Pourcentage de remise</th>
									<th>Prix</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								<% @items.each do |item| %>
									<%= render partial: "administration/items/table_row", locals: {item: item} %>
								<% end %>
							</tbody>
						</table>
					</div>
				</div>

			</div>
		</div>

	</div>
</main>